### ISSUE TITLE
ReferenceError: serverCredentials is not defined

### ISSUE THREAD

**Issue by fsiddiqi** [jasonruane/node-red-contrib-blockchain#1]
Hi - 

Great idea!  Exactly what I was thinking of building, but found your node.

Creating and submitting the Tierion hash item API works great and I get the PASS result and receipt as expect.

However, on invoking verify, I get a reference error in the debug console.  Specifically:
  ReferenceError: serverCredentials is not defined

On inspecting node-red-contrib-blockchain-verify.js, I couldn't tell where serverCredentials was being set.

I'd be happy to debug and send a PR if you're interested, but wanted to check with you first

Thanks

Faisal

**Comment by jasonruane** [comment]
Hi Faisal,
thank you for reaching out.
Glad you liked it - it was just a small idea which I wrote for the fun of
it.

As for server credentials, I am currently working on something else so
won't be able to get to it until tomorrow. I think the credentials need to
be entered in the verify block also. ie. double click the verify module and
set the config there to also have the credentials. Or, I may have put them
in a "global" variable at the submission block and then reused them at the
verification block. That is a guess though.

If you do find the solution and it requires code changes, please do submit
a Pull Request as I have never actually received one before. I don't use
git much, just for the occasional node-red stuff.
I received an email from someone else about the verification part so I will
forward that email to you now in case that helps too.

thanks again for reaching out.
Jason

**Comment by jasonruane** [comment]
---------- Forwarded message ----------

Date: Mon, Nov 14, 2016 at 6:08 PM
Subject: Blockchainverify node error
To: jason.ruane@gmail.com


Hi Jason,
Was trying out your Blockchain nodes (Tierion) in Node-RED. First one works
fine, but second one (verify) keeps giving this error.

ReferenceError: serverCredentials is not defined

11/14/2016, 10:02:54 AM38a82727.ed3b38msg.payload : Object{ "dataToHash":
"Car Available, John, Contract Stop, GPS2", "tierionHashHex": "
a8001c4c856f0ff8c944d70d150dbf9fc131d43a0333cbc48058e8af77dac8c3",
"tierionReceiptId": "5829fc4e64cd05042ac3fba4", "tierionTimestamp":
1479146574, "result": "PASS" }
11/14/2016, 10:03:10 AMa165d1be.9fb9amsg : string [79]hash value is:
a8001c4c856f0ff8c944d70d150dbf9fc131d43a0333cbc48058e8af77dac8c3
11/14/2016, 10:03:10 AMa165d1be.9fb9amsg : string [28]Already logged in to
Tierion
11/14/2016, 10:03:10 AMa165d1be.9fb9amsg : errorReferenceError:
serverCredentials is not defined

**Comment by fsiddiqi** [comment]
Looks good - thanks
